version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=ppp
      - POSTGRES_PASSWORD=ppp
      - POSTGRES_DATABASE=ppp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
      name: "ppp-postgres"